baseurl: https://la-liga-economica.netlify.app/
title: La liga económica
theme: hugo-universal-theme
languageCode: en-us
defaultContentLanguage: es
disqusShortname: devcows
googleAnalytics: ''
summaryLength: 70
paginate: 10
menu:
  main:
    - identifier: menu.home
      name: Inicio
      url: /
      weight: 1
    - identifier: menu.temas
      name: Temas
      url: /img/template-easy-customize.png
      weight: 2
    - identifier: section.teoria
      name: "Teoría económica"
      parent: menu.temas
      post: 1
      url: ''
      weight: 1
    - name: "Microeconomía"
      parent: section.teoria
      url: ''
      weight: 1
    - name: "Macroeconomía"
      parent: section.teoria
      url: ''
      weight: 2
    - name: "Mesoeconomía"
      parent: section.teoria
      url: ''
      weight: 3
    - identifier: section.aplicada
      name: "Economía aplicada"
      parent: menu.temas
      post: 2
      url: ''
      weight: 2
    - name: "Modelos para México"
      parent: section.aplicada
      url: ''
      weight: 1
    - name: "Modelos para otros países"
      parent: section.aplicada
      url: ''
      weight: 2
    - name: "Modelos multipaíses"
      parent: section.aplicada
      url: ''
      weight: 3
    - identifier: section.otros
      name: "Otros"
      parent: menu.temas
      post: 1
      url: ''
      weight: 3
    - name: "Estadística"
      parent: section.otros
      url: /categories/estadistica/
      weight: 2
    - identifier: section.coyuntura
      name: "Coyuntura"
      parent: menu.temas
      post: 2
      url: ''
      weight: 4
    - name: "Indicares recientes"
      parent: section.coyuntura
      url: ''
      weight: 1
    - identifier: menu.blog
      name: Blog
      url: /blog/
      weight: 5
    - identifier: contacto
      name: Contacto
      url: /contact/
      weight: 7
    - identifier: quienessomos
      name: Quiénes somos
      url: /about_us/
      weight: 8
  topbar:
    - name: Phone
      pre: <i class='fas fa-2x fa-phone'></i>
      url: tel:+12 34 567 89 01
      weight: 1
    - name: GitHub
      pre: <i class='fab fa-2x fa-github'></i>
      url: https://github.com/devcows/hugo-universal-theme
      weight: 2
    - name: Facebook
      pre: <i class='fab fa-2x fa-facebook'></i>
      url: http://facebook.com
      weight: 3
    - name: Twitter
      pre: <i class='fab fa-2x fa-twitter'></i>
      url: http://twitter.com
      weight: 4
    - name: Email
      pre: <i class='fas fa-2x fa-envelope'></i>
      url: mailto:hello@universal.com
      weight: 5
params:
  about_us: <p>Pellentesque habitant morbi tristique senectus et netus et malesuada
    fames ac turpis egestas.</p>
  address: "<p class=\"text-uppercase\"><strong>Universal Ltd.</strong>\r\n        <br>13/25
    New Avenue\r\n        <br>Newtown upon River\r\n        <br>45Y 73J\r\n        <br>England\r\n
    \       <br>\r\n        <strong>Great Britain</strong>\r\n      </p>\r\n      "
  author: la-liga-economica
  carouselCustomers:
    auto_play: no
    items: 6
    pagination_speed: 1000
    slide_speed: 2000
  carouselHomepage:
    auto_play: yes
    enable: no
    pagination_speed: 1000
    slide_speed: 2000
  carouselTestimonals:
    auto_play: no
    items: 4
    pagination_speed: 1000
    slide_speed: 2000
  clients:
    enable: no
    subtitle: ''
    title: Our Clients
  contact_form_ajax: no
  contact_url: /contact
  copyright: Copyright (c) 2015 - 2016, YourCompany; all rights reserved.
  date_format: 2 de January de 2006
  default_sharing_image: img/sharing-default.png
  defaultDescription: Site template made by devcows using hugo
  defaultKeywords:
    - devcows
    - hugo
    - go
  disabled_logo: no
  enableGoogleMaps: yes
  enableRecaptchaInContactForm: no
  facebook_site: ''
  features:
    cols: 3
    enable: yes
  footer:
    recent_posts:
      enable: yes
  formspree_action: https://formspree.io/sample/of/endpoint
  googleMapsApiKey: AIzaSyAv7Sza8NSp9_l_g8G2vlo0H4ydEPn_2jY
  googleRecaptchaKey: site_key_for_google_recaptcha
  latitude: '-12.043333'
  logo: img/logo-ligaeconomica.png
  logo_small: img/logo-ligaeconomica.png
  logo_text: "La liga económica"
  longitude: '-77.028333'
  mainSections: blog
  recent_posts:
    enable: yes
    hide_summary: no
    subtitle: Pellentesque habitant morbi tristique senectus et netus et malesuada
      fames ac turpis egestas. Vestibulum tortor quam, feugiat vitae, ultricies eget,
      tempor sit amet, ante. Donec eu libero sit amet quam egestas semper. Aenean
      ultricies mi vitae est. Mauris placerat eleifend leo.
    title: Nuestro blog
  see_more:
    enable: yes
    icon: far fa-file-alt
    link_text: Quienes somos
    link_url: '/about_us/'
    subtitle: Somos un grupo de egresados de la facultad de economía de la UNAM, interesados en temas actuales de economía y estadística.
    title: ¿Quiénes somos?
  style: marsala
  testimonials:
    enable: no
    subtitle: We have worked with many clients and we always like to hear they come
      out from the cooperation happy and satisfied. Have a look what our clients said
      about us.
    title: Testimonials
  topbar:
    enable: no
    text: "<p class=\"hidden-sm hidden-xs\">Contact us on +420 777 555 333 or hello@universal.com.</p>\r\n
      \     <p class=\"hidden-md hidden-lg\"><a href=\"tel:+420 777 555 333\" data-animate-hover=\"pulse\"><i
      class=\"fas fa-phone\"></i></a>\r\n      <a href=\"mailto:hello@universal.com\"
      data-animate-hover=\"pulse\"><i class=\"fas fa-envelope\"></i></a>\r\n      </p>\r\n
      \     "
  twitter_site: GoHugoIO
  viewMorePostLink: /blog/
  widgets:
    categories: yes
    search: yes
    tags: yes
permalinks:
  blog: /blog/:year/:month/:day/:filename/
taxonomies:
  author: authors
  category: categories
  tag: tags
